name: Deploy Dist folder
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      # - run: |
      #     echo "Cloning repo"
      #     echo "${{ toJson(github) }}"
      #     git clone https://github.com/${{ github.repository }}.git myfiles
      #     cd myfiles && ls
